apiVersion: batch/v1
kind: Job
metadata:
  name: copychaincodeversion
spec:
  backoffLimit: 1
  template:
    metadata:
      name: copychaincodeversion
    spec:
      restartPolicy: "Never"
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: filepvc
      
      containers:
      - name: copychaincodeversion
        image: alpine:3.7
        imagePullPolicy: Always
        command: ["sh", "-c", "ls -l /shared; rm -rf /shared/artifacts/chaincode; ls -l /shared; while [ ! -d /shared/artifacts/chaincode ]; do echo Waiting for new chaincode to be copied; sleep 2; done; sleep 10; ls -l /shared/artifacts/chaincode; "]
        volumeMounts:
        - mountPath: /shared
          name: myvolume